const greetings = {
  Arabic: 'مرحبا',
  Bengali: 'হ্যালো',
  Chinese: '你好',
  Czech: 'Ahoj',
  Danish: 'Hej',
  Dutch: 'Hallo',
  Finnish: 'Hei',
  French: 'Bonjour',
  German: 'Hallo',
  Greek: 'Γεια σας',
  Hebrew: 'שלום',
  Hindi: '',
  Hungarian: 'Helló',
  Indonesian: 'Halo',
  Italian: 'Ciao',
  Japanese: 'こんにちは',
  Korean: '안녕하세요',
  Malay: 'Halo',
  Norwegian: 'Hallo',
  Polish: 'Cześć',
  Portuguese: 'Olá',
  Romanian: 'Salut',
  Russian: 'Здравствуйте',
  Spanish: 'Hola',
  Swedish: 'Hej',
  Tagalog: 'Kamusta',
  Thai: 'สวัสดี',
  Turkish: 'Merhaba',
  Ukrainian: 'Привіт',
  Vietnamese: 'Xin chào',
};

export default greetings;
